import { memo, useState, useEffect, useMemo } from 'react';
import { highlight, tone } from '../ui';
// car base name -> image file, generated by tools/car-images (images themselves live on the VPS under /cars/)
import carImages from '../car-images.json';

function Value({ v }) {
  if (!v.text) return <span className="empty">—</span>;
  if (v.pair) return <>{v.pair[0]}<span className="sep">/</span>{v.pair[1]}</>;
  return v.text;
}

// "4-5階, 曼巴套件" -> "4-5階 · 曼巴套件"; a tune without a suffix is the standard one.
const variantLabel = (tune) => (tune.variant ? tune.variant.split(/\s*[,，]\s*/).join(' · ') : '標準');

// One car, fully visible (no expanding). A car with several tunes (tiers, ECU, kits) gets a switch;
// the card shows the selected tune: the first sheet section (改裝方向) as cells, the others side by side.
export default memo(function CarCard({ model, sections, q }) {
  const [sel, setSel] = useState(0);
  // A search that matches only some variants (e.g. "曼巴") selects the first of them.
  const preferred = useMemo(() => {
    if (!q || model.tunes.length < 2 || model.base.toLowerCase().includes(q)) return -1;
    return model.tunes.findIndex((t) => t.variant?.toLowerCase().includes(q));
  }, [q, model]);
  useEffect(() => { if (preferred >= 0) setSel(preferred); }, [preferred]);
  const image = carImages[model.base];
  const [imageFailed, setImageFailed] = useState(false);

  const car = model.tunes[Math.min(sel, model.tunes.length - 1)];
  const [tune, ...specs] = sections;
  return (
    <article className={`card tone-${tone(model.cls)}`}>
      {image && !imageFailed && (
        <div className="card-media">
          <img src={`/cars/${image}`} alt="" width="560" height="232" loading="lazy" decoding="async" onError={() => setImageFailed(true)} />
        </div>
      )}
      <div className="card-head">
        <h3 className="card-name">{highlight(model.base, q)}</h3>
        <span className="badge">{model.cls}</span>
      </div>
      {model.tunes.length > 1 && (
        <div className="variants" role="group" aria-label="調校版本">
          {model.tunes.map((t, i) => (
            <button key={t.id} type="button" className="variant" aria-pressed={t === car} onClick={() => setSel(i)}>
              {highlight(variantLabel(t), q)}
            </button>
          ))}
        </div>
      )}
      {((model.tunes.length === 1 && car.variant) || car.updated) && (
        <p className="card-meta">
          {model.tunes.length === 1 && car.variant && <span className="tag">{highlight(car.variant, q)}</span>}
          {car.updated && <time dateTime={car.updated}>更新 {car.updated}</time>}
        </p>
      )}
      {tune && (
        <div className="tune">
          <h4 className="section-label">{tune.title}</h4>
          <div className="tune-cells">
            {tune.fields.map((f, i) => (
              <div className="cell" key={f.col}>
                <span className="cell-label">{f.label}</span>
                <span className="cell-value"><Value v={car.values[0][i]} /></span>
              </div>
            ))}
          </div>
        </div>
      )}
      {specs.length > 0 && (
        <div className="specs">
          {specs.map((s, si) => (
            <div className="spec" key={s.title}>
              <h4 className="section-label">{s.title}</h4>
              <dl>
                {s.fields.map((f, fi) => (
                  <div className="row" key={f.col}>
                    <dt>{f.label}{f.hint && <small>{f.hint.join('/')}</small>}</dt>
                    <dd><Value v={car.values[si + 1][fi]} /></dd>
                  </div>
                ))}
              </dl>
            </div>
          ))}
        </div>
      )}
    </article>
  );
});
